name: Unittests
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  run-unittests:
    name: Execute unittests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        run: pdm install

      - name: Run unittests
        run: pdm run test
